export const CLEAR_DATA = "CLEAR_DATA";
//API CALLS
export const GET_STOCK_SUCCESS = "GET_STOCK_SUCCESS";
export const GET_REQUEST = "GET_REQUEST";
export const GET_REQUEST_FAILURE = "GET_REQUEST_FAILURE";
//INPUTS
export const SET_SEARCH = "SET_SEARCH";
export const SET_DATE = "SET_DATE";
//TRADE FORM
export const SET_TRADE_SYMBOL = "SET_TRADE_SYMBOL";
export const SET_TRADE_PRICE = "SET_TRADE_PRICE";
export const SET_TRADE_DATE = "SET_TRADE_DATE";
export const SET_TRADE_QUANTITY = "SET_TRADE_QUANTITY";
export const SET_TRADE_BUY = "SET_TRADE_BUY";
export const SET_CASH = "SET_CASH";
//TRANSACTIONS
export const SET_TRANSACTION = "SET_TRANSACTION";
export const CLEAR_TRANSACTION_TRADE = "CLEAR_TRANSACTION_TRADE";
